config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :photo, presence: true

  # монтируем загрузчик фотографий
  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # Для каждого действия нужно получить событие, к которому привязана фотография
  before_action :set_event, only: [:create, :destroy]

  # Для действия destroy нужно получить из базы саму фотографию
  before_action :set_photo, only: [:destroy]
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def create
    # Создаем новую фотографию у нужного события @event
    @new_photo = @event.photos.build(photo_params)
    # Проставляем у фотографии пользователя
    @new_photo.user = current_user

    if @new_photo.save
      SendEmailJob.perform_later(@new_photo)
      # Если фотографию удалось сохранить, редирект на событие с сообщением
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      # Если фотографию не удалось сохранить, рендер события с ошибкой
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  # Действие для удаления фотографии
  def destroy
    message = {notice: I18n.t('controllers.photos.destroyed')}

    # Проверяем, может ли пользователь удалить фотографию
    # Если может — удаляем, нет, меняем сообщение
    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('controllers.photos.error')}
    end

    # И в любом случае редиректим его на событие
    redirect_to @event, message
  end

  private

  # Так как фотография — вложенный ресурс, то в params[:event_id] рельсы
  # автоматически положат id события, которому принадлежит фотография
  # найденное событие будет лежать в переменной контроллера @event
  def set_event
    @event = Event.find(params[:event_id])
  end

  # Получаем фотографию из базы стандартным методом find
  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  # При создании новой фотографии мы получаем массив параметров photo
  # c единственным полем (оно тоже называется photo)
  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%# Форма для добавления новой фотографии с одним полем photo %>
<%# Обратите внимание на параметр multipart %>
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="form-group flex-column">
    <%= f.label :photo, 'Фото' %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<%# Паршал для вывода отдельной фотографии %>
<div class="event-photo buffer-both d-inline">
  <% unless photo.photo.blank? %>
    <% image_title = "Добавил #{render partial: 'users/user', object: photo.user}" %>
    <% if current_user_can_edit?(photo) %>
      <% image_title += " #{link_to fa_icon('trash'), event_photo_path(photo.event, photo), method: :delete, data: {confirm: 'Точно удалить?'}}" %>
    <% end %>

    <a href="<%= photo.photo.url %>" data-lcl-txt="<%= image_title %>" data-lcl-author="" class="mybox">
      <img src="<%= photo.photo.thumb.url %>">
    </a>
  <% end %>
</div>